import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Providers from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Providers>
					<section className="flex">
						<div className="h-screen w-[220px] shadow-[0_4px_10px_rgba(0,0,0,0.65)]">
							<nav>
								{/* <div></div> */}
								<ul>
									<Link
										href={"/"}
										className="flex h-[50px] w-ful items-center justify-center transition-colors duration-50 hover:bg-gray-300"
									>
										Geral
									</Link>
									<Link
										href={"/empresas"}
										className="flex h-[50px] w-ful items-center justify-center transition-colors duration-50 hover:bg-gray-300"
									>
										Empresas
									</Link>
									<Link
										href={"/documentos"}
										className="flex h-[50px] w-ful items-center justify-center transition-colors duration-50 hover:bg-gray-300"
									>
										Documentos
									</Link>
								</ul>
							</nav>
						</div>
						{children}
					</section>
				</Providers>
			</body>
		</html>
	);
}
